### ISSUE TITLE
Pre-release r2dii.data 0.0.1.9001

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.data#11]
Prepare for release: 

* [x] Check that DESCRIPTION is informative 
* [x] Check licensing of included files
* [x] `usethis::use_cran_comments()` 
* [x] `devtools::check(remote = TRUE, manual = TRUE)` 
* [ ] `devtools::check_win_devel()` 
* [x] `rhub::check_for_cran()` 2020-03-16
   * https://builder.r-hub.io/status/r2dii.data_0.0.1.9001.tar.gz-023382fe3c604a26892982bd9c890658
   * https://builder.r-hub.io/status/r2dii.data_0.0.1.9001.tar.gz-cc1d8b671234402799a013cd16a66d04
   * https://builder.r-hub.io/status/r2dii.data_0.0.1.9001.tar.gz-e8210f75a3ab4780802483adba51fd13
* [x] Update `cran-comments.md` 
* [x] Review pkgdown reference index for, e.g., missing topics 
 
Submit to CRAN: 
 
* [ ] `usethis::use_version('patch')` 
* [ ] `devtools::submit_cran()` 
* [ ] Approve email 
 
Wait for CRAN... 
 
* [ ] Accepted :tada: 
* [ ] `usethis::use_github_release()` 
* [ ] `usethis::use_dev_version()` 
* [ ] `usethis::use_news_md()` 
* [ ] Update install instructions in README

**Comment by maurolepore** [comment]
@jdhoffa, please see find your name next to the check-boxes above. When you are done, please let me know and I'll submit. If you want we can do it together (just for fun).

The build of the website is currently failing so the package website right now is outdated. The problem seems not ours but of pkgdown. I suspect it'll fix itself over the next few hours. If not I can build the site locally and push it.

**Comment by jdhoffa** [comment]
My proposed changes to the description:
```
Description: These datasets support the implementation in R of
    the software 'PACTA' (Paris Agreement Capital Transition Assessment),
    which is a free tool that calculates the alignment between financial
    assets and climate scenarios (<https://www.transitionmonitor.com/>).
    Financial institutions use 'PACTA' to study how their capital allocation
    impacts the climate. Because both financial institutions and market data 
    providers keep their data private, this package provides fake, public data 
    to enable the development and use of 'PACTA' in R.
```

**Comment by jdhoffa** [comment]
I can confirm that all data is fake.

**Comment by jdhoffa** [comment]
I confirm that the GNU license is correct for all files and work in this package.
