### ISSUE TITLE
SIC codes sector bridge 

### ISSUE THREAD

**Issue by georgeharris2deg** [2DegreesInvesting/r2dii.data#120]
I would like to map my client to the sectors as defined by PACTA. My Bank uses SIC codes and hence it would be good to have a SIC codes bridge. 
Attached is an excel of the codes and their descriptions. 
[SIC codes and descriptions.xlsx](https://github.com/2DegreesInvesting/r2dii.data/files/4931206/SIC.codes.and.descriptions.xlsx)

@jdhoffa 
@daisy-pacheco

**Comment by maurolepore** [comment]
Thanks @georgeharris2deg, I copied the .xlsx file to .csv [here](https://gist.github.com/maurolepore/120759548227700ae8971aa3f256e453).

**Comment by jdhoffa** [comment]
IN GISTS! that makes so much sense.

**Comment by jdhoffa** [comment]
@georgeharris2deg we might be able to convince the banks to do something similar should they choose to add new sector bridges

**Comment by jdhoffa** [comment]
@daisy-pacheco

**Comment by daisy-pacheco** [comment]
Hi all, I'm attaching a file with a first sector classification, for your review. Please reach out in case you have comments or questions.

[SIC codes and descriptions.xlsx](https://github.com/2DegreesInvesting/r2dii.data/files/4954515/SIC.codes.and.descriptions.xlsx)

**Comment by maurolepore** [comment]
Daisy's file as [.csv](https://gist.github.com/maurolepore/14092dd1256e49b18e7929402cd3b7f2).

``` r
path <- "https://gist.githubusercontent.com/maurolepore/14092dd1256e49b18e7929402cd3b7f2/raw/d12b30be758759032875e0fe2cc96576abffd085/sic_codes_daisy.csv"
janitor::clean_names(readr::read_csv(path))
#> Parsed with column specification:
#> cols(
#>   SIC = col_character(),
#>   SIC_DESCRIPTION = col_character(),
#>   `not in scope` = col_double(),
#>   `in scope maybe` = col_double(),
#>   `in scope for sure` = col_double(),
#>   sector = col_character()
#> )
#> # A tibble: 256 x 6
#>    sic   sic_description     not_in_scope in_scope_maybe in_scope_for_su… sector
#>    <chr> <chr>                      <dbl>          <dbl>            <dbl> <chr> 
#>  1 0     Private Households…            0              0                0 <NA>  
#>  2 00000 Private Households…            0              0                0 <NA>  
#>  3 11110 Growing Of Cereals…            1              0                0 <NA>  
#>  4 11130 Growing Of Fruit, …            1              0                0 <NA>  
#>  5 11210 Farming  Of Cattle…            1              0                0 <NA>  
#>  6 11300 Growing Of Crops C…            1              0                0 <NA>  
#>  7 12100 Forestry And Relat…            1              0                0 <NA>  
#>  8 12200 Logging And Relate…            1              0                0 <NA>  
#>  9 13100 Ocean And Coastal …            1              0                0 <NA>  
#> 10 21000 Mining Of Coal And…            0              0                1 oil a…
#> # … with 246 more rows
```

<sup>Created on 2020-07-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
