### ISSUE TITLE
Where should we keep small- to medium- size REAL datasets

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.data#122]
There are a number of "real" auxiliary datasets, that are used by the `r2dii` suite. These datasets are not large enough, nor do they change frequently enough, to warrant being explicitly passed as an argument, however we should try to define/ manage where these data should live. 

Concretely, I'm thinking of datasets such as: 
``` r
library(r2dii.data)
library(r2dii.analysis)

# exported data from r2dii.data
r2dii.data::isic_classification %>% head()
#> # A tibble: 6 x 4
#>   code  code_level sector       borderline
#>   <chr>      <dbl> <chr>        <lgl>     
#> 1 A              1 not in scope FALSE     
#> 2 1              2 not in scope FALSE     
#> 3 11             3 not in scope FALSE     
#> 4 111            4 not in scope FALSE     
#> 5 112            4 not in scope FALSE     
#> 6 113            4 not in scope FALSE

r2dii.data::region_isos %>% head()
#> # A tibble: 6 x 3
#>   region             isos  source  
#>   <chr>              <chr> <chr>   
#> 1 advanced economies bg    weo_2019
#> 2 advanced economies hr    weo_2019
#> 3 advanced economies cy    weo_2019
#> 4 advanced economies mt    weo_2019
#> 5 advanced economies ro    weo_2019
#> 6 advanced economies au    weo_2019

# internal data in r2dii.analysis
r2dii.analysis:::pick_tmsr_or_smsp %>% head()
#> # A tibble: 6 x 3
#>   sector     technology    which_metric                   
#>   <chr>      <chr>         <chr>                          
#> 1 automotive electric      smsp_target_weighted_production
#> 2 automotive hybrid        smsp_target_weighted_production
#> 3 automotive ice           tmsr_target_weighted_production
#> 4 automotive fuelcell      smsp_target_weighted_production
#> 5 power      hydrocap      smsp_target_weighted_production
#> 6 power      renewablescap smsp_target_weighted_production
```

<sup>Created on 2020-07-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The criteria of the data I'm thinking of are the following: 
* Publicly available
* Fewer than a couple hundred rows, and no more than 10 columns

@maurolepore when we have some breathing room, lets have a discussion about this and see what we can think of. I know you brought this up a while ago, but i'd like to keep it on our radar

**Comment by maurolepore** [comment]
I think such datasets seem to fit comfortably within scope of r2dii.data.

![image](https://user-images.githubusercontent.com/5856545/88185305-64ffc380-cbf9-11ea-8735-16f604ed043d.png)

I don't remember what I suggested before, but I now lean towards including them in r2dii.data. This is what we currently do; and it seems okay as the datasets are relevant and small.

**Comment by jdhoffa** [comment]
Ok perfect. Initially you had expressed a desire to separate the "real" and "fake/ demo" datasets. 
Let's continue on like that for now then, and in the case that this becomes unruly/ difficult to handle, we can split them apart perhaps

**Comment by maurolepore** [comment]
Awesome, I'm proud that this time I was able to overcome the common psychological problem by which humans would rather die than prove themselves wrong. :)

Does this close the issue?

**Comment by jdhoffa** [comment]
Nope! 
We still need to move the datasets created in 2DegreesInvesting/r2dii.analysis#135 to r2dii.data. 
I will do so this morning :)
