### ISSUE TITLE
In demo datasets, "ton" and "tons" should be "tonne" and "tonnes"

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.data#133]
We are always referring to a tonne, defined as 1000 kg (or a metric ton). 
A bit nit-picky, but good to be consistent.

**Comment by jdhoffa** [comment]
Thanks @georgeharris2deg

**Comment by maurolepore** [comment]
This was closed by https://github.com/2DegreesInvesting/r2dii.data/pull/134
