### ISSUE TITLE
GICS sector bridge 

### ISSUE THREAD

**Issue by georgeharris2deg** [2DegreesInvesting/r2dii.data#162]
Need to add a GICS sector classification bridge. 

It is a common classification system and one of the road testers is requesting it. 

resources:
https://www.msci.com/gics
[GICS_map 2018.xlsx](https://github.com/2DegreesInvesting/r2dii.match/files/5293303/GICS_map.2018.xlsx)

@georgeharris2deg to make the bridge 
@jdhoffa @maurolepore to upload to r2dii.data

**Comment by jdhoffa** [comment]
Moved this to `r2dii.data` as that is the repo it will touch

**Comment by georgeharris2deg** [comment]
Attached is the GICS to PACTA sector bridge. 
This is based on the excel file in the initial issue above
I have left in the GICS descriptions and would appreciate it if someone could have a quick double-check to see that I haven't missed any. 
I followed the template of the other Bridges - however,
I am now not clear of the purpose of the borderline column - hence I have left it blank here. 

[gics_pacta.xlsx](https://github.com/2DegreesInvesting/r2dii.data/files/5318397/gics_pacta.xlsx)

Thanks, and please let me know if you have any questions. 
George

**Comment by maurolepore** [comment]
Thanks @georgeharris2deg!

**Comment by jdhoffa** [comment]
Im on this now, will have a PR open soon

**Comment by georgeharris2deg** [comment]
@maurolepore do you know when we might be able to push this to CRAN by? - a bank needs it and can pull from GitHub due to internal firewalls. - thanks
