### ISSUE TITLE
Serialization round-trip is not symmetric.

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.data#176]
Thanks to waldo and testthat 3e I  have a clue for what might be  causing tests to fail on fine data.

<img src=https://user-images.githubusercontent.com/5856545/98980753-e4c7db80-24d1-11eb-8c36-41f21e1af2b9.png width=500>
I don't know the process well but it seems like the data that gets saved and later retrieved is a lil different -- doubles seems to differ after their 8th decimal place.

I'm not sure what's the best approach -- maybe we so something like 

```r
expect_snapshopt_value(round_all_double_columns_to_8_decimal_places(data), style = "json2")
```

**Comment by jdhoffa** [comment]
That is very weird.

**Comment by maurolepore** [comment]
Maybe it relates to the number of decimal places in my options()?
