### ISSUE TITLE
Change structure of developer facing files from .csv to .tsv?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.data#189]
https://mastering-shiny.org/action-transfer.html#downloading-data

> I recommend using .tsv (tab separated value) instead of .csv (comma separated values) because many European countries use commas to separate the whole and fractional parts of a number (e.g. 1,23 vs 1.23). This means they can’t use commas to separate fields and instead use semi-colons in so-called “c”sv files! You can avoid this complexity by using tab separated files, which work the same way everywhere.

**Comment by jdhoffa** [comment]
I don't agree with this. My reasoning is as follows: 
If you read in two `.tsv` files, one of which uses a `,` decimal separator, and the other uses a `.` decimal separator, you will have no indication of which is which. If you were to then, for example, `rbind` these datasets, you would silently end up with an inconsistent dataframe. 

In the `,` and `;` convention of `.csv`, we at least have an indication, on read, of which decimal separator is used, and can potentially create a system to account for this, and unify the files to the `.` decimal separator. 

Feel free to comment if you disagree!

**Comment by maurolepore** [comment]
That’s a good point. I wonder the tidy folks would think

**Comment by jdhoffa** [comment]
I see you reopened this, do you still think this is a desirable enhancement?

**Comment by maurolepore** [comment]
Sorry.
