### ISSUE TITLE
Sector bridge - PSIC

### ISSUE THREAD

**Issue by daisy-pacheco** [2DegreesInvesting/r2dii.data#199]
Hello all!

We have another sector classification bridge to include in the r2dii.data package. This time this is the Philippine Standard Industrial Classification (PSIC), used by one of the banks that has just started with the implementation of PACTA for banks.

Please find attached the file with the corresponding info. Let me know if there is any question or comment.

Thanks a lot!
Daisy

@georgeharris2deg 
@Lauramirez-2ii 
[NSCB_PACTA_bridge.xlsx](https://github.com/2DegreesInvesting/r2dii.data/files/5913348/NSCB_PACTA_bridge.xlsx)

**Comment by maurolepore** [comment]
Thanks! 

@daisy-pacheco can you please check this version looks right? Just to confirm that importing it into a more portable format did not corrupt the data.


https://docs.google.com/spreadsheets/d/1WsVAeVqqFDRDg5IdeDSssXzG1EBD2L0Enho5jhWfczM/edit?usp=sharing

(Whenever you can, please prefer  a google sheet or .cvs -- I don't even have Excel in my Linus system.)

**Comment by daisy-pacheco** [comment]
Hey Mauro, it looks good to me, only that the Borderline column changed to
Spanish...

I tried to upload it as .csv, but I couldn't. Github throws out this
message when I try to do it:

[image: Screenshot 2021-02-02 at 19.20.57.png]

Let me know if there is anything else I can do.

Thanks!
Daisy

**Comment by maurolepore** [comment]
Thanks! 

RE: The translation to Spanish, Could it be just on your end? I don't seem to see that here:
![image](https://user-images.githubusercontent.com/5856545/106645737-615adb00-6552-11eb-92fc-9b6f2039d6dd.png)


@jdhoffa, expect a PR (or stop me I you think otherwise).

**Comment by daisy-pacheco** [comment]
Ah! interesting, apparently it is in Spanish only for me: "FALSO" and
somewhere down "VERDADERO". But I guess not a problem since you see the
correct format. Thanks a lot :)
[image: Screenshot 2021-02-02 at 19.32.21.png]

**Comment by maurolepore** [comment]
FYI, coming soon via #200:

``` r
library(dplyr, warn.conflicts = FALSE)

r2dii.data::sector_classifications %>% 
  filter(code_system == "PSIC")
#> # A tibble: 1,270 x 4
#>    sector       borderline code  code_system
#>    <chr>        <lgl>      <chr> <chr>      
#>  1 not in scope FALSE      01111 PSIC       
#>  2 not in scope FALSE      01112 PSIC       
#>  3 not in scope FALSE      01113 PSIC       
#>  4 not in scope FALSE      01114 PSIC       
#>  5 not in scope FALSE      01119 PSIC       
#>  6 not in scope FALSE      01121 PSIC       
#>  7 not in scope FALSE      01122 PSIC       
#>  8 not in scope FALSE      01123 PSIC       
#>  9 not in scope FALSE      01130 PSIC       
#> 10 not in scope FALSE      01140 PSIC       
#> # … with 1,260 more rows
```

<sup>Created on 2021-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by daisy-pacheco** [comment]
Hello all, 

We've been facing some issues regarding the matching process of the RCBC Bank's portfolio with the ALD data. We thought that it might be related to some 0s that precede the sector classification codes in the file I shared here a couple of weeks ago. 

We would like to ask you how feasible is it for you to upload it again, so we can try and see if that is actually the problem or not.

RCBC is also doing some checks to see if the problem might be actually related to their classification in their loan book, but we wanted to cover all possible options, so next session we can try again to solve the issue.

I am attaching here the sector bridge file again.

Please let us know if you have any questions or comments. Thanks a lot!
Daisy

@georgeharris2deg 
@Lauramirez-2ii 

[NSCB_PACTA_bridge_1.xlsx](https://github.com/2DegreesInvesting/r2dii.data/files/5989497/NSCB_PACTA_bridge_1.xlsx)

**Comment by maurolepore** [comment]
Thanks! Do you have some concrete deadline?

@jdhoffa, considering that the bridge is quite commonly updated, I wonder if we should allow users to pass their own (unless we already do it?).

**Comment by georgeharris2deg** [comment]
Hi @maurolepore we need this done ASAP ideally - I would say the hard deadline is next Monday - I hope that is manageable?

@maurolepore @jdhoffa - I back Mauro's idea of allowing a user to use there own bridge - not sure how much work this would be but it would indeed circumvent the need for us to do this all the time and allow a user to use their internal classification systems

**Comment by maurolepore** [comment]
@daisy-pacheco and @georgeharris2deg can you please show the problem you face? Best would be a [reprex](https://reprex.tidyverse.org/) but a call or any detail you can provide might help. 

To check if I understand correctly, the .xlsx file you attach has the "offending" ceros removed, right? Is it online on a google sheet I could quickly see and compare with the previous one?

**Comment by daisy-pacheco** [comment]
@maurolepore I think doing a reprex would be a bit difficult, since the error was being showed in the R session of the bank's person doing the analysis. We could only saw it this morning on our video call.

If I recall correctly, there was an error message telling us that no match was being done.

And yes, the file I am attaching is the one with the zeros removed. 

https://docs.google.com/spreadsheets/d/1FaF9IoH0NerVw8-OF7pFvdFSiy9vbmpSQ9ZwQUeEr7k/edit?usp=sharing

Please let me know if you can see the document now. Sorry once again, I cannot seem to be able to share .csv files in here.

**Comment by maurolepore** [comment]
Thanks!

Note to self: The difference between the two files is in the column "code". Compare:

on CRAN:
<img src=https://i.imgur.com/gnyA9Va.png width=200>

Proposed: 
<img src=https://i.imgur.com/DGq2Kzu.png width=200>

--

@daisy-pacheco, it would be useful to know if the problem they experience is fixed by 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(r2dii.data)

packageVersion("r2dii.data")
#> [1] '0.1.7'

sector_classifications %>% 
  filter(code_system == "PSIC") %>% 
  mutate(code2 = as.integer(code)) %>% 
  select(code, code2)
#> # A tibble: 1,270 x 2
#>    code  code2
#>    <chr> <int>
#>  1 01111  1111
#>  2 01112  1112
#>  3 01113  1113
#>  4 01114  1114
#>  5 01119  1119
#>  6 01121  1121
#>  7 01122  1122
#>  8 01123  1123
#>  9 01130  1130
#> 10 01140  1140
#> # … with 1,260 more rows
```

<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
