### ISSUE TITLE
update "r2dii.data::region_isos" to accommodate new scenarios 

### ISSUE THREAD

**Issue by georgeharris2deg** [2DegreesInvesting/r2dii.data#241]
As we introduce new scenarios from new scenario providers we need new regional bridges. 

2 optiosn exist here iether separate files for region bridge specific to scenario input. 
eg "new_scenrio_input_file" must be used with "new_secanrio_region_file" 
or 
the already existing "r2dii.data::region_isos" accommodates for all scenarios. 

the latter is preferred as it reduces the number of files needed. 

So what we would need is to add new sources to "r2dii.data::region_isos" currently there is only "weo_2019" and "etp_2017" 

what we need now is 
region          isos                source 
example       example         weo_2019
                                           etp_2017 
                                           weo_2020 
                                           ieanze_2021
                                           nzaoa_2020 

exact names in source column to be given by @Antoine-Lalechere  - naming standard to be agreed upon in comments below 
@Antoine-Lalechere please provide the bridges here 

note that what ever is in r2dii.data::region_isos - column "source" muct = the column "scenario_source" in the scenario input file 

@jdhoffa @maurolepore @Antoine-Lalechere

**Comment by jdhoffa** [comment]
Currently, `regions` are defined individually in the folder `./data-raw/region_isos_SCENARIO_NAME`, so you would need to add a new `.csv` file there (ideally formatted similarly to the other datasets there, maybe use `region_isos_weo_2019` as an example). 

Then, one would have to edit the file `data-raw/region_isos.R`. This is the file that is used to source all of the raw region data in `data-raw/`, and export it through the package. This could be a little more tricky, as there are some things that occur in this script that are slightly confusing (for instance, dealing with regions that are defined as containing other regions). 

But hopefully this is enough to start on for now, and i can help when I'm back on PACTA next week.

**Comment by Antoine-Lalechere** [comment]
@maurolepore I have neither access to this folder so I can't upload the `regions_isos_SCENARIO_NAME` file, can you give me access to it? :)

**Comment by maurolepore** [comment]
@jdhoffa what would be your preferred way to go about this?

1. Is this an issue you think should be addressed?
2. If so, what would be your preferred way to address it? 
    - 2.a. Accept a direct contribution form @Antoine-Lalechere
    - 2.b. Create some structure for the contribution then ask @Antoine-Lalechere to edit the structure you built?
    - 2.c. Something else?

--
I'm happy to do things myself but only with specific instructions form @jdhoffa as he's the one how better understands not only this package but also the potential consequences in the r2dii ecosystem.
