### ISSUE TITLE
ald_scenario_demo

### ISSUE THREAD

**Issue by 2diiKlaus** [2DegreesInvesting/r2dii.data#32]
### Describe the dataset
This dataset is the starting point of any PACTA analysis, including the bank's methodology. It can be used for matching as well as for the analysis itself. The dataset includes the asset level data connected to the scenario data. It is thus the result of the combination of ald_demo and scenario_demo (the latter doesn't exist yet).

The following data points are needed: 

- scenario_source
- ald_company_sector_id
- scenario
- id_name
- id
- domicile_region
- scenario_region
- ald_sector
- technology
- year
- production (formerly plan_tech_prod)
- emission_intensity (formerly plan_emission_factor)
- scenario_production (formerly scen_tech_prod)
- scenario_emission_intensity (formerly scen_emission_factor)
- current_plan_row
- scenario_exists

### Additional context

[Add screenshots](https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests) or any other context about the dataset here.

### Data dictionary entry

dataset | column | typeof | definition
-- | -- | -- | --
ald_scenario_demo | scenario_source | character | Defining   the source of the scenario (e.g. WEO2019)
ald_scenario_demo | ald_company_sector_id | integer | Company   ID allocated by 2dii, per sector each ID is unique. This allows tracing the company back in the asset level data as well as in the company ownership tree
ald_scenario_demo | scenario | character | Abbreviation   of the scenario (e.g. Sustainable development scenario = SDS)
ald_scenario_demo | id_name | character | Name of the ID provided in the id column. The id is used for mapping of the   dataset to a given portfolio (for credit: company_name, for corporate bonds:   corporate_ticker and for equity: bloomberg_id
ald_scenario_demo | id | character | The financial instrument-specific id, that defines the company   (or corporate bond pool). At this level, the asset level data got aggregated
ald_scenario_demo | domicile_region | character | The domicile region (or country) in which the company defined   by the id is located
ald_scenario_demo | scenario_region | character | The region of the production (the asset location). It is   aggregated to the regions given by the scenarios to allow the application of the regional   scenario pathway
ald_scenario_demo | ald_sector | character | The climate-relevant sector, where the company has production   capacities in (a single company can have production capacities in several   sectors
ald_scenario_demo | technology | character | the technology within the sector for which the company has   production capacities
ald_scenario_demo | year | double | Year of the production capacity
ald_scenario_demo | production | double | Production capacity of the company for the technology, year,   in the scenario region etc.
ald_scenario_demo | emission_intensity | double | average emission intensity of the production for this technology in the given region, etc.
ald_scenario_demo | scenario_production | double | production capacity that the company needs to have to follow   the scenario trendline
ald_scenario_demo | scenario_emission_intensity | double | average emission intensity of the production for this   technology in the given region under the given scenario roadmap
ald_scenario_demo | current_plan_row | logical | Flag that identifies if the company has production capacities in the start year of the analysis. True = it has production, False =it doesn't
ald_scenario_demo | scenario_exists | logical | Flag that identifies if a scenario exists for the given regions, technology, year

**Comment by Clare2D** [comment]
Good morning. I don't know what the difference is calculating the Global Agg... If we don't need it then I would say drop it... this is probably a statement I'll regret though.

**Comment by 2diiKlaus** [comment]
haha :D @Clare2D 
It would still be possible to calculate it quickly: sum capacity by region and divide by the global capacity. Same for the technology share. 

I will remove them for now. I think it is easier to add columns than removing them

**Comment by jdhoffa** [comment]
This all exists more or less. 
`r2dii.scenario::raw_scenario_demo` for actual raw scenario data
`r2dii.scenario::scenario_demo_2020` for scenario data, prepared for a start_year = 2020
Scenario preparation functions are in `r2dii.scenario` and we will be pulling `r2dii.scenario::scenario_demo_2020` into `r2dii.data` when it is a little more mature (see https://github.com/2DegreesInvesting/r2dii.data/issues/28) 

As for the combined file being the start of the banks analysis, that is fine, but the function to do this joining also already exists. Rather than write a "new" raw dataset that is just the output of 
```r
 valid_matches %>% join_ald_scenario(ald_demo, scenario_demo)
``` 
(or some middle-step of that function), I'd rather just extract the necessary function from `r2dii.analysis` to whichever package you are planning on using to do the data preparation for the banks. 

@2diiKlaus I can't today, but lets have a call about this on wednesday?

**Comment by jdhoffa** [comment]
@maurolepore 
- [ ] Rename columns of `ald_demo` as per @2diiKlaus's [comment](https://github.com/2DegreesInvesting/r2dii.data/pull/24#issuecomment-606408655)
- [ ] Add columns `mutate(id_name = "company_name")`, `mutate(ald_emission_factor_unit = glue::glue(sector, "emission_factor"))`
- [ ] Forget about the optional column `New ald_demo$company_name`
- [ ] Join `scenario_demo_2020` in with the `New ald_demo` (similar to how `r2dii.analysis::join_ald_scenario()` does)
- [ ] Call this file `ald_scenario_demo`

Relates to #24
