### ISSUE TITLE
Fix encoding (?) in website's home

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.data#36]
@cjyetman this this look like an encoding problem during the creation of the website (via pkgdown)? 

README.md seems fine:

![](http://i.imgur.com/Tp2WoSM.png)

But the website is not:

![](http://i.imgur.com/fEs9B1K.png)

**Comment by maurolepore** [comment]
Seems that we should wait until someone else fixes this problem -- which is clearly not just ours
![](http://i.imgur.com/83p5ydr.png)

**Comment by cjyetman** [comment]
Looks like this is probably fixed in https://github.com/r-lib/xml2/commit/654385789de3ac2ee08d05555a32147eb8a12457

and on CRAN already [xml2 v131](https://cran.rstudio.com/web/packages/xml2/)

**Comment by maurolepore** [comment]
Great! I upgraded to xml2 v131 and built a correctly-encoded site via `pkgdown::deploy_to_branch()` locally and on gh actios.

https://2degreesinvesting.github.io/r2dii.match/

Thanks for your help @cjyetman, I'm closing now.
