### ISSUE TITLE
Bring scenario_demo_2020 from r2dii.scenario

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.data#37]
See https://github.com/2DegreesInvesting/r2dii.scenario/blob/master/data-raw/scenario_demo.R

**Comment by jdhoffa** [comment]
make sure that it's `scenario_demo_2020` that comes out! it must be prepared by the year

**Comment by maurolepore** [comment]
Okay, so 

`r2dii.scenario::scenario_demo` -> `r2dii.data::scenario_demo_2020`

**Comment by maurolepore** [comment]
Add `scenario_demo_2020`

* [ ] Add "data-raw/scenario_demo_2020.csv" 
* [ ] Add "data-raw/data_dictionary/scenario_demo_2020.csv" 
* [ ] In "data-raw/scenario_demo_2020.R", add something like: 
  ```
  # Source: @<contributor> <URL to issue or pull request>
  scenario_demo_2020 <- readr::read_csv(here::here("data-raw", "scenario_demo_2020.csv"))
  use_data(scenario_demo_2020, overwrite = TRUE)
  ```
* [ ] `usethis::use_r("scenario_demo_2020")`. Document `scenario_demo_2020` 
* [ ] `usethis::use_test("scenario_demo_2020")`. Add regression tests of `scenario_demo_2020` 
* [ ] `source("data-raw/data_dictionary.R"); devtools::load_all()` 
* [ ] `usethis::use_test("data_dictionary")`. Test `data_dictionary` includes `scenario_demo_2020`

**Comment by jdhoffa** [comment]
1. Done
2. We do not, I want to work on this file a bit more before including in `r2dii.data`
3. Almost complete. 

TODO: 
- [ ] Add `@format` to `scenario_demo_2020.R` (I wasn't sure how you systematically generate this from the data_dictionary entry, could you show me?)

a. `r2dii.scenario` is unstable and `r2dii.scenario::raw_scenario_demo` is unstable, however `scenario_demo_2020` is stable (in my opinion). Any changes to how we generate this file shouldn't change the format of the file, this is why i felt comfortable including it in `r2dii.data`. We could try to remove the dependency on `r2dii.scenario::add_market_share_columns()` altogether by including only `scenario_demo_2020.csv` itself in `data-raw`, what do you think?

**Comment by maurolepore** [comment]
> We could try to remove the dependency on r2dii.scenario::add_market_share_columns() altogether by including only scenario_demo_2020.csv itself in data-raw, what do you think?

I'm not worried about the dependency because we call from data-raw/, which isn't checked by R CMD check. I'm worried about not being able to reproduce `scenario_demo_2020.csv` later on, or to  reproduce but with a lot of work, like digging in the git repo of r2dii.scenario for a commit that can indeed reproduce.

To be safe and clean I suggest this:

* [ ] Ensure r2dii.scenario passes R CMD check cleanly
* [ ] Increment the dev version number, tag the commit, and create a github release
* [ ] Copy the relevant code to r2dii.data and commit. This ensures that whatever happens with 
  r2dii.scenario (even if we kill the repo) the code will be easy to recover.
* [ ] Remove the relevant code and point to the code in r2dii.scenario as we do now, except that
  we can link to the specific github release (i.e. git tag).i
* [ ] Sleep well.

**Comment by jdhoffa** [comment]
Release 0.0.9001 of `r2dii.scenario` now stable-ish (passes `R CMD check`) boo-yah.
