### ISSUE TITLE
Align `region_isos` to the definitions in the WEO2019

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.data#49]
Currently the `region_isos` defined are those from a previous WEO. I doubt much has changed, but we will need to ensure that all scenario region definitions align with those described in WEO_2019. 

We should also add a column specifying that these definitions are specific to the WEO2019.

**Comment by maurolepore** [comment]
@jdhoffa please send me the private document that defines the regions.

**Comment by maurolepore** [comment]
@jdhoffa said we also want to add the new column `source`, a value would be e.g. "2020".

**Comment by jdhoffa** [comment]
the column should be `source` and the value should `weo2019` for every row
