### ISSUE TITLE
Update `scenario_demo_2020` to include CO2_emissions sectors (e.g. aviation)

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.data#54]
Currently `scenario_demo_2020` (and correspondingly `ald_scenario_demo`) only reflect sectors with technology pathways (e.g. `automotive`, `oil and gas`, `power`) but must include also CO2 emission intensities for `aviation`, `automotive`, `cement`, `steel`, etc. so that we can adequately test.

**Comment by maurolepore** [comment]
@jdhoffa I assign to you because I suspect you'll start a PR on this. Otherwise please detail what to do :+1:

**Comment by jdhoffa** [comment]
Nope no worries, I will handle this!
