### ISSUE TITLE
Rename `source` to `region_definition_source`

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.data#56]
`source` is used a multiple times by other datasets to indicate different things. Better to be more precise in this case I think. 

Also I know for a fact that `source` doesn't touch any other function yet, so this is not a breaking change.

**Comment by maurolepore** [comment]
I'm not sure about this change. What's the main problem you anticipate?
* From a technical point of view it's generally easy to refer to variables in specific datasets.
* And from a conceptual point of view, this seems to try give low a level interface (the dataframe) too much knowledge about how it will be used at higher levels.

**Comment by jdhoffa** [comment]
No you're right, fair point. 
The problem arises when joining a valid_matches object (which has the column "source" depicting if the matches were manual or not) and the ald_scenario object (which shows the source definition for each region). 

In hindsight, I think it's actually ok to just drop the region `source` on the joined dataset. 

Happy to close this.
