### ISSUE TITLE
Remove the explicit @format section in each helpfile

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.data#63]
The explicit `@format` section we use in this package is redundant with `data_dictionary`, uncommon (AFAIK), and makes the package just a bit harder to maintain. We included it to please CRAN in the first release. We could remove it in any patch release with a clean R CMD check.

**Comment by jdhoffa** [comment]
It's a little odd that this is a CRAN requirement, but isn't commonplace amongst packages no?

**Comment by maurolepore** [comment]
Thanks for your challenging question. I looked for examples and I learned it's more common than I thought:

* > @format gives an overview of the dataset. For data frames, you should include a definition list that describes each variable. It’s usually a good idea to describe variables’ units here. --http://r-pkgs.had.co.nz/data.html#data-data

* For example see the section Format at https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/mtcars

So I would revert and try find a way to generate the columns definition on the fly when we `document()`. The tag `@eval` seems promising; it allows to run arbitrary code (https://roxygen2.r-lib.org/articles/rd.html#do-repeat-yourself). 

Sorry for not doing my research before.

**Comment by jdhoffa** [comment]
All good. I should also do my own research! 
I just tend to trust you as the de-factor R guru ;)

**Comment by maurolepore** [comment]
The saying goes "trust but verify".

**Comment by maurolepore** [comment]
This was closed by #73 but #79 reverts (ish) it in a more maintainable way.
