### ISSUE TITLE
Should we use either prefixes or suffixes?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.data#67]
Often we need to express which dataset a column comes from. Sometime we use a prefix and other times we use a suffix. 

1. Should we aim to be consistent?
1. Should we pick either prefixes or suffixes?

``` r
library(r2dii.data)
library(r2dii.match)
library(dplyr, warn.conflicts = FALSE)

# To express which dataset a variable comes from ...

# ... here we us a prefix
ald_demo %>% 
  select(matches("ald")) %>% 
  names()
#> [1] "ald_timestamp"

# ... here we use a suffix
match_name(loanbook_demo, ald_demo) %>% 
  select(matches("ald")) %>% 
  names()
#> [1] "sector_ald" "name_ald"
  
# ... here we use a prefix
scenario_demo_2020 %>% 
  select(matches("scenario")) %>% 
  names()
#> [1] "scenario"        "scenario_source"
```

<sup>Created on 2020-05-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jdhoffa** [comment]
Ya makes sense to be consistent. I don’t really have a preference between prefix or suffix. Prefix makes more sense from an English syntax perspective I think?

**Comment by maurolepore** [comment]
Okay, so from an English syntax perspective, +1 to data as prefix (e.g. "region_source").

The one thing I thought about is the order in which columns appear when we sort the column names. For example:

Using data as prefix, we make it easy to order columns by dataset name: 

_"ald_name", "ald_source", "region_source"_

Using data as suffix, we make it easy to order columns by column name: 

_"name_ald", "source_ald", "source_region"_

Do you have any thoughts about this?

**Comment by jdhoffa** [comment]
This is difficult. I can imagine both cases useful for different contexts.

**Comment by jdhoffa** [comment]
suffixes already exist in `match_name()` so maybe best to stick with that approach

**Comment by maurolepore** [comment]
This is stale.
