### ISSUE TITLE
Prune package for next CRAN release

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.data#86]
For instance, remove `ald_scenario_demo`

**Comment by maurolepore** [comment]
I think we can close this PR. 

* I excluded `ald_scenario_demo` and re-added it in a draft-PR (https://github.com/2DegreesInvesting/r2dii.data/pull/90) for us to consider re-including it after we get downstream packages to a stable state.
* I considered removing the internal function `defint()`. And I proposed adding a version of it in r2dii.usethis via https://github.com/2DegreesInvesting/r2dii.usethis/pull/22. But I now think it may be best to keep r2dii.data self-contained. So keep using `define()` here.
* I considered moving `source_data_raw()` elsewhere. But I think for now it's best to keep things simple and self-contained.

Closing now. See #91
